fix(gcrouter): breaking changes removed * from access control allow o…
gcsns/gc-router pull request #8
Opened 2021-11-30 13:01 UTC by taran1898

2021-11-30 13:27 UTC, suresh-saini commented on lib/router.js
> +    static initialize(app, config, container, allowedOrigin) {
please do the changes to ts files. js files are created by compiling ts files

2021-11-30 13:27 UTC, suresh-saini commented on lib/middleware.js
> +        response.status(status).json(Object.keys(error).length === 0 ? { message: error.message } : error);
please do the changes to ts files. js files are created by compiling ts files

2021-12-01 11:11 UTC, suresh-saini requested changes
please also run build so that generated files are updated based on ts changes

2021-12-01 11:11 UTC, suresh-saini commented on src/router.ts
> +                    res.setHeader('Access-Control-Allow-Origin', `${allowedOrigin}`);
why don't you use `allowedOrigin` directly?

2021-12-01 11:14 UTC, taran1898 commented on src/router.ts
> +                    res.setHeader('Access-Control-Allow-Origin', `${allowedOrigin}`);
We can't have null as a value for this. Refer doc https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null

2021-12-01 11:14 UTC, taran1898 commented
> please also run build so that generated files are updated based on ts changes

Already done.

2021-12-01 11:29 UTC, suresh-saini commented on lib/middleware.js
> +        response.status(status).json(Object.keys(error).length === 0 ? { message: error.message } : error);
I am not saying about condition. I am saying about ``${allowedOrigin}\``

2021-12-01 11:30 UTC, suresh-saini commented on src/router.ts
> +                    res.setHeader('Access-Control-Allow-Origin', `${allowedOrigin}`);
I am not saying about condition. I am saying about ``${allowedOrigin}\``

2021-12-01 12:58 UTC, suresh-saini approved these changes

2021-12-01 12:58 UTC, merged